language: python

python:
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip setuptools
  - pip install coveralls
  - pip install flake8
  - pip install .

script:
  - python setup.py test
  - flake8 viper/ tests/

after_success:
- coveralls
